esphome:
  name: dayled
  friendly_name: DayLED

esp8266:
  board: esp01_1m

# Enable logging
logger:

ota:
  - platform: esphome
    password: "abc123"

wifi:
  ssid: Somewhere Else
  password: notmypassword

light:
  - platform: neopixelbus
    type: GRB
    variant: ws2812x
    pin: GPIO2
    num_leds: 108
    id: prog_strip
    initial_state:
      state: False
    effects:
      - addressable_lambda:
          name: "Day progress"
          update_interval: 100ms
          lambda: |-
            static Color BLUE = Color(0, 128, 192);
            static Color ORANGE = Color(192, 96, 0);
            auto time = id(sntp_time).now();
            int step = ((time.hour - 9) * 3600 + time.minute * 60 + time.second) / 200;
            if ( step >= 0 && step <= it.size() ) {
              it.range(0, step) = BLUE;
              if ( initial_run ) {
                it.range(step, it.size()) = ORANGE;
              }
            }
      - addressable_rainbow:
          name: Rainbow
          speed: 100
          width: 40

time:
  - platform: sntp
    id: sntp_time
    timezone: Pacific/Auckland
    servers:
      - 0.nz.pool.ntp.org
      - 1.nz.pool.ntp.org
      - 2.nz.pool.ntp.org
    on_time:
      - hours: 9-13
        seconds: /10
        days_of_week: MON-FRI
        then:
          - light.turn_on:
              id: prog_strip
              effect: "Day progress"
      - hours: 14
        minutes: 0-57
        seconds: /10
        days_of_week: MON-FRI
        then:
          - light.turn_on:
              id: prog_strip
              effect: "Day progress"
      - hours: 14
        minutes: 58
        seconds: 0
        then:
          - light.turn_on:
              id: prog_strip
              effect: Rainbow
      - hours: 14
        minutes: 58
        seconds: 15
        then:
          - light.turn_off:
              id: prog_strip
