esphome:
  name: dining-heatpump
  friendly_name: dining-heatpump

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "emswpoq9XhCORJjqIZRMv0yaKluFHkJ76mEOPBU+aZY="

ota:
  - platform: esphome
    password: "c43ca2dfeb89660fee00c3e040e117c0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dining-Heatpump Fallback Hotspot"
    password: "BOWwr3wthvj6"

web_server:
  port: 80

captive_portal:

remote_receiver:
  id: rcvr
  pin:
    number: GPIO4
    inverted: true
    mode:
      input: true
      pullup: true
  tolerance: 55%

remote_transmitter:
  pin:
    number: GPIO3
    inverted: true
    mode:
      input: true
      pullup: true
  carrier_duty_percent: 50%

climate:
  - #platform: daikin
    platform: fujitsu_general
    name: "Dining Room A/C"
    receiver_id: rcvr
